### ISSUE TITLE
how can user add new cowsay file?

### ISSUE THREAD

**Issue by Freed-Wu** [iwataka/cowsay.vim#1]
![image](https://user-images.githubusercontent.com/32936898/80867272-fd0aa280-8cc5-11ea-83f3-7247d575f828.png)

thanks!

**Comment by iwataka** [comment]
Thanks for opening issue!
Unfortunately there is no recommended approach now but one workaround exists.

You can add a `xxx.cow` file to `/path/to/cowsay.vim/cowsay/cows/` directory and then call `cowsay#cowsay('any text', 'xxx')` in Vim.

**Comment by Freed-Wu** [comment]
can it provide a variable like `g:cowsay#source_paths`, when user
```
let g:cowsay#source_paths=['/path/to/user_self_cowsay_source_file', '/path/to/schacon/cowsay']
```
it will search source from these paths?

**Comment by iwataka** [comment]
I implemented this feature, so please check README and try the latest version. @Freed-Wu

**Comment by Freed-Wu** [comment]
Thanks!
